Collections/Message: add close button
circuithub/elm-semantic-ui pull request #15
Opened 2019-02-12 09:20 UTC by domenkozar

2019-02-12 09:26 UTC, ocharles requested changes

2019-02-12 09:26 UTC, ocharles commented on SemanticUI/Collections/Message.elm
> +                closeContent ++
This is in both branches so I think we should move it outside the `case` statement.

2019-02-12 09:27 UTC, ocharles commented on SemanticUI/Collections/Message.elm
> +                  [ i [ class "close icon"
Could we use `SemanticUI.Elements.Icon` here?

2019-02-13 07:39 UTC, domenkozar commented
I think I've addressed the review, thanks Ollie :)

2019-02-13 08:28 UTC, merged

2019-02-13 08:28 UTC, ocharles commented
Thanks!